### ISSUE TITLE
MQTT/MQTT.h No Such File

### ISSUE THREAD

**Issue by mtngit14** [hirotakaster/MQTT#11]
MQTT test firmware compiles (and flashed Photon) in Particle cloud but not in desktop Particle Dev.
Changing the include to just #include "MQTT.h" allowed compiling/flashing in Particle Dev. 
Note program and includes all located in same flat directory.
Could someone validate this change as a correct solution and not really changing some other parameter.
Particle Dev on MacBook Pro with El Capitan 10.11.1 

David
RavenTT / MiqroMeq

**Comment by timpulver** [comment]
Had the same issue with latest Particle Dev on Mac OS X El 10.11.1 and the Neopixel library – putting all files into the same folder as the main file (no subfolders) worked.

**Comment by hirotakaster** [comment]
I think this problem is based Spark Deve desktop client.
