### ISSUE TITLE
QOS1 (at least half-one)

### ISSUE THREAD

**Issue by SadE54** [hirotakaster/MQTT#14]
Currently , it seems only QOS 0 is supported by the library. The problem is that even if you're subscribing with a client and a persistent connection, the broker never sends the offline messages because of QOS0 used for publishing. But it's often needed to store the sensor data at the broker level , and then be able to retrieve all data from a client.
So, QOS1 at leasdt is needed to fulfill that.
Complete implementation of QOS1 could be complicated due to RAM limitation (but it shoud be possible if we know the average payload length and limit the number of messages that can be stored).
But maybe one trick could be used : just be able to add the flag for QOS1 when a message is published . If the message is received by broker , a PUBACK is sent back , and we do not even need to process it . If it's not received by the broker , it's lost. 
But the received messages with QOS1 flag are stored on the broker and then can be used with persistent connections at the other end.

**Comment by hirotakaster** [comment]
Hi, than you checking. I will update that it can change qos flag when application publish the message.
