### ISSUE TITLE
Publish with QOS and Retain

### ISSUE THREAD

**Issue by alistairg** [hirotakaster/MQTT#16]
It's possible I'm missing something - but how would I publish a message with a QOS of 2, and the retain flag set?

**Comment by alistairg** [comment]
I can see you added support for QOS1 and QOS2, but not retain on publish..... ?

**Comment by hirotakaster** [comment]
QoS1 and QoS2 don't need retain flag, there is not correlation QoS and retain flag. check MQTT V3.1 Protocol Specification.
http://public.dhe.ibm.com/software/dw/webservices/ws-mqtt/mqtt-v3r1.html
