### ISSUE TITLE
Support for retain flag on published messages

### ISSUE THREAD

**Issue by alistairg** [hirotakaster/MQTT#22]
There is no way to set the "retain" flag on any message other than the "Will" on initial connect

**Comment by hirotakaster** [comment]
If want to use retain flag, set kep is true following function.
publish(const char* topic, const uint8_t* payload, unsigned int plength, bool kept)
publish(const char* topic, const uint8_t* payload, unsigned int plength, bool kept, EMQTT_QOS qos, uint16_t *messageid)

**Comment by alistairg** [comment]
My apologies. I looked at the example (mqttqostest.ino) rather than the source. :)
