### ISSUE TITLE
MQTT_MAX_PACKET_SIZE too small

### ISSUE THREAD

**Issue by jrburk** [hirotakaster/MQTT#34]
MQTT_MAX_PACKET_SIZE is too small for my application. Would it be a big deal to make it configurable with the constructor or a setter?

The constant is used four times in MQTT.cpp. Could be replaced with sizeof(buffer) ?

**Comment by hirotakaster** [comment]
Hi, now I update configure the max_packet_size at constructor.  18b66728b969e13a63751c26ee417ee2d37216b1 commit no.

**Comment by jrburk** [comment]
Thank you!

**Comment by hirotakaster** [comment]
may be you can use on Particle IDE(version 0.3.8) soon.
can I close this issue?

**Comment by jrburk** [comment]
yes
