### ISSUE TITLE
Please acknowledge PubSubClient

### ISSUE THREAD

**Issue by knolleary** [hirotakaster/MQTT#35]
Hi,

it appears this library is based largely on my PubSubClient library.

However this library makes no reference that I can see of my library or the appropriate copyright. Please refer to the license I share my library under; you are free to use the code, you just have to acknowledge where it came from.

https://github.com/knolleary/pubsubclient/blob/master/LICENSE.txt 

> The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

Nick

**Comment by hirotakaster** [comment]
Hi, oh, It's a sorry.
I wrote your license on MQTT.h header file, but I forget write lisence file. 
Now I update lisence.txt file, please check this.

**Comment by hirotakaster** [comment]
Hi, @knolleary 
Does it Okay? Can I close this?

**Comment by knolleary** [comment]
Thanks for addressing!
