### ISSUE TITLE
QOS not editable in client.publish() 

### ISSUE THREAD

**Issue by ilsocio87** [hirotakaster/MQTT#36]
Hi! 
Great library.
I just wanted to let you know that in MQTT.cpp all the parameters referring to QOS in client.publish() function are hard-coded to QOS0. This is resulting in qos0 for all messages even if someone sets different QOS with the public class MQTT::QOS.

```
bool MQTT::publish(const char * topic, const char* payload, EMQTT_QOS qos, uint16_t *messageid) {
    return publish(topic, (uint8_t*)payload, strlen(payload), false, QOS0, messageid);
} 
```

Cheers!

Simone

**Comment by hirotakaster** [comment]
Hi ilsocio87,
Thank you for checking this QoS issue. This is bug.
Now I update bug fixed version to 0.4.0.
