### ISSUE TITLE
  initializing argument 2 of 'bool MQTT::publish(const char*, const char*, MQTT::EMQTT_QOS, uint16_t*)' [-fpermissive]

### ISSUE THREAD

**Issue by mhelgren** [hirotakaster/MQTT#41]
Veryfing code using this library in Particle Build fails with this error:
```
MQTT/MQTT.h:163:10: error:   initializing argument 2 of 'bool MQTT::publish(const char*, const char*, MQTT::EMQTT_QOS, uint16_t*)' [-fpermissive]
     bool publish(const char *, const char *, EMQTT_QOS, uint16_t *messageid = NULL)

**Comment by hirotakaster** [comment]
@mhelgren , I can compile on Photon, Core WebIDE and I did not version up. code is like this,

  client.publish("outTopic/message", "hello world QOS1", MQTT::QOS1, &messageid);

check your code or sample .ino.

**Comment by hirotakaster** [comment]
@mhelgren hi, close this issue?

**Comment by mhelgren** [comment]
Yes you can close it.  Thanks.
