### ISSUE TITLE
  initializing argument 2 of 'bool MQTT::publish(char*, char*)' [-fpermissive]

### ISSUE THREAD

**Issue by dande011** [hirotakaster/MQTT#5]
Veryfing code using this library in Particle Build fails with this error:
```
MQTT/MQTT.h:113:9: error:   initializing argument 2 of 'bool MQTT::publish(char*, char*)' [-fpermissive]
    bool publish(char *, char *)

```
Here is the line that is causing it trouble:
```
client.publish("hello/world", (topic == "/home/test")?"TRUE":"FALSE");
```
I don't know if the conditional operator is doing something unexpected, but it should just show up as "TRUE" or "FALSE", as far as the function call can see.

**Comment by hirotakaster** [comment]
let's try like this. 

  client.publish("hello/world", (topic == "/home/test") ? (char *)"TRUE" : (char *)"FALSE");

**Comment by jeffeb3** [comment]
These arguments should be "const char *", not "char *" There's no reason you would need to edit them. This should be changed in the library.

**Comment by hirotakaster** [comment]
now update to 7e711af0d0d332dc23e5b1d681a0fe00a4500b90
