### ISSUE TITLE
Particle Build failed compilation when target is new 0.6.2 firmware

### ISSUE THREAD

**Issue by th3j3ster** [hirotakaster/MQTT#57]
When using the online Particle IDE and attempting to build a project including this libary, if the device firmware (for the photon) is set to "0.6.2" or "Default(0.6.2)", the compiler throws an error:
```
/workspace/lib/MQTT/src/MQTT.cpp:83:18: error: ambiguous overload for 'operator=' (operand types are 'String' and 'int')
     this->domain = NULL;
```

This appears to have just started today; I'm assuming that 0.6.2 was released yesterday.

**Comment by hirotakaster** [comment]
hi @th3j3ster ,
Oh, okay, thank you. I will fix this.

**Comment by hirotakaster** [comment]
I update 0.4.17 and fixed this.

**Comment by th3j3ster** [comment]
Working great, thanks!
