### ISSUE TITLE
Could you migrate this lib to v2.0 format please?

### ISSUE THREAD

**Issue by ScruffR** [hirotakaster/MQTT#59]
To support the Particle Library Manager all new publishes should feature v2.0 structure.

The easiest to get there is via CLI
```
particle library migrate
```

**Comment by hirotakaster** [comment]
hi @ScruffR ,
I update with `particle library migrate` command, and I have to fixe&update on Particle IDE library manager too?

**Comment by hirotakaster** [comment]
And I will go to SFO on this weekend with my exhibit at Maker Faire Bay Area 2017. So maybe I might be delayed reply, sorry.

**Comment by hirotakaster** [comment]
hi @ScruffR 
Now I update to version 0.1.8 with migrate command. thx.
