### ISSUE TITLE
Support for clean session

### ISSUE THREAD

**Issue by AndrewWeiss** [hirotakaster/MQTT#61]
I don't see any support for cleanSession.  Given that microcontrollers spend a lot of time offline, I would like to make sure any "commands" that I want to send to the device while it's offline are received when the device comes back online.

Any recommendations on how to add this support?

**Comment by AndrewWeiss** [comment]
Answering my own question.  Check the pull requests.  It's been added

**Comment by hirotakaster** [comment]
hi @AndrewWeiss ,
I added clean session flag and update & publish to particle library.
