### ISSUE TITLE
client.connect() blocks argon in SYSTEM_THREAD(ENABLED)

### ISSUE THREAD

**Issue by Lurow** [hirotakaster/MQTT#78]
Hi there,

I recently played around with the new "mesh" line from particle and used this lib.
At first, it was fine, everything was working as expected, but when we tried to enable threading and moved the `client.connect()` into the `loop(){}` block it appears to block all incoming connections.

```
if(!client.isConnected()){
            client.connect("bar");
            client.subscribe("foo");
}
```

is there any practice or solution for this problem?

best regards

**Comment by Lurow** [comment]
Saw some problems with string IPs in one of the pull requests. Changing it to IPAddress resolved the issue

**Comment by hirotakaster** [comment]
that's problem is already resolved in MQTT.h files.
